module.exports = [
    {
      address: '184 Kent Ave',
      apt_num: 'A515',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11249,
      neighborhood: 'Williamsburg',
      borough: 'Brooklyn',
      status: 'Available',
      property_type: 'Condo',
      bedrooms: 2,
      bathrooms: 2,
      price: 1775000,
      square_feet: 1086,
      price_per_sq_ft: 1634,
      description:
        "Welcome to The Austin Nichols House, a luxurious waterfront condominium in the heart of Williamsburg. This stunning 2 bed, 2 bath Loft boasts 12' beamed ceilings, high-end finishes, and smart home integration, making it the perfect place to call home. This unique corner-unit features an open-concept living and dining area with large, luminous windows that flood the space with natural light from both southern and eastern exposures, and beautiful oak herringbone floors. Custom designer kitchen from Vipp with top-of-the-line appliances, including a Gaggenau cooktop and range with professional quality range hood and Liebherr fridge. The spacious primary bedroom boasts custom closet and an en-suite designer bathroom with high-end finishes and rain shower. The second bedroom is equally spacious and is conveniently located adjacent to the second full bathroom. This unit also includes in-unit Miele washer/dryer, central air conditioning, and smart home features, including a Nest thermostat, Ring doorbell, and Lutron lighting and shades. Residents of The Austin Nichols House enjoy access to a host of amenities, including a the most impressive gym you have ever seen with waterfront and skyline views, furnished rooftop terrace with grills, a newly designed children’s playroom, resident’s lounge for entertainment or work-from-home, music room with piano, library, movie theater, and serene zen-garden. The building has 24 hour concierge, doorman, live-in super and quite possibly the best staff around. Located right near the best restaurants, shops, and nightlife that Williamsburg has to offer, as well as easy access to transportation with the L train and the Ferry. Don't miss your chance to own this stunning loft apartment in one of Brooklyn's most sought-after buildings.",
      image_url:
        'https://www.compass.com/m/0/6e8b595c-5100-49ce-b94f-9e8d3252cd7a/1500x1000.jpg',
    },
    {
      address: '255 West 23rd St',
      apt_num: '4HW',
      city: 'New York',
      state: 'NY',
      zip_code: 10011,
      neighborhood: 'Chelsea',
      borough: 'Manhattan',
      status: 'Available',
      property_type: 'Co-op',
      bedrooms: 2,
      bathrooms: 1,
      price: 1495000,
      square_feet: 0,
      price_per_sq_ft: 0,
      description:
        "Fall in love instantly with this stunning two bedroom home, meticulously renovated with wide planked oak floors, exposed brick walls, cast iron columns, and soundproof windows. This expansive layout is over 1,000sf with sunny southern exposure and has a separate dining area. The open kitchen has a Sub-Zero fridge, Viking range, and Meile dishwasher, as well as a wine fridge. The extra-large primary bedroom can easily accommodate a king sized bed and the closets are huge! The second bed is currently being used as an office, but goes both ways. There is also a separate dining area, beautifully designed bathroom, and several extra closets. Located on 23rd St between 7th and 8th at Chelsea Gardens, which is made up of two art deco style buildings with a gorgeous common garden in between. There is a 24 hour doorman, live-in super, elevators, laundry, bike room, and storage. Quite possibly the most convenient location in Manhattan. Right next to the red and blue lines, only a short walk to the orange and yellow lines. Close to Whole Foods, Trader Joes, every furniture and home store you could want, and of course the high line. If you would like to arrange a private showing, let me know and I'll make it happen.",
      image_url:
        'https://www.compass.com/m/0/d44366c0-e9d8-4eef-a6b1-c8545025b41d/1500x1000.jpg',
    },
    {
      address: '11 West 18th St',
      apt_num: '5E',
      city: 'New York',
      state: 'NY',
      zip_code: 10011,
      neighborhood: 'Flatiron',
      borough: 'Manhattan',
      status: 'Coming Soon',
      property_type: 'Co-op',
      bedrooms: 3,
      bathrooms: 1,
      price: 1695000,
      square_feet: 0,
      price_per_sq_ft: 0,
      description:
        "Rarely Available Flatiron Loft with No Monthly Maintenance! This is a true loft apartment with high ceilings, and approx 1,300sf of space, currently configured as a 3 bedroom. The huge eat-in-kitchen has a large skylight overhead, stainless appliances, lots of counter and cabinet space. In addition, this apartment comes with an in-unit washer/dryer and 2 private storage spaces downstairs, including bicycle and stroller parking. Located on West 18th and 5th, this amazing Flatiron Loft resides in one of the most highly desired locations in Manhattan. It doesn't get more convenient being this close to Union Square, the farmer's market, and easy access to virtually every subway line you could possibly ask for. Contact me now for a private showing. With no monthly maintenance payment, I expect this to go quickly.",
      image_url:
        'https://www.compass.com/m/0/b386be52-9b19-4a04-9573-20205f0e2905/1500x1000.jpg',
    },
    {
      address: '82 Irving Pl',
      apt_num: '5D',
      city: 'New York',
      state: 'NY',
      zip_code: 10003,
      neighborhood: 'Gramercy',
      borough: 'Manhattan',
      status: 'Sold',
      property_type: 'Co-op',
      bedrooms: 1,
      bathrooms: 1,
      price: 810000,
      square_feet: 0,
      price_per_sq_ft: 0,
      description:
        'Welcome home to this beautifully renovated 1 bedroom on Irving Place, ...',
      image_url:
        'https://www.compass.com/m/LISTING_EDITOR/putImages/9a84268b-698c-4e10-...',
    },
    {
      address: '210 Riverside Dr',
      apt_num: '2C',
      city: 'New York',
      state: 'NY',
      zip_code: 10025,
      neighborhood: 'Upper West Side',
      borough: 'Manhattan',
      status: 'Sold',
      property_type: 'Co-op',
      bedrooms: 2,
      bathrooms: 1,
      price: 901000,
      square_feet: 0,
      price_per_sq_ft: 0,
      description:
        'This gorgeous apartment features extra-large rooms, high ceilings, and...',
      image_url:
        'https://www.compass.com/m/30c0552903eb40d3999523c31874255f543f4f6c_img...',
    },
    {
      address: '790 President St',
      apt_num: '2L',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11215,
      neighborhood: 'Park Slope',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Co-op',
      bedrooms: 2,
      bathrooms: 1,
      price: 827500,
      square_feet: 0,
      price_per_sq_ft: 0,
      description:
        'Live on a quiet tree lined street in a classic pre-war brownstone loca...',
      image_url:
        'https://www.compass.com/m3/0064da6ecc16f19137d3ad0d654d39c565559b66/64...',
    },
    {
      address: '184 Kent Ave',
      apt_num: 'A204',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11249,
      neighborhood: 'Williamsburg',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 1,
      bathrooms: 1,
      price: 889000,
      square_feet: 646,
      price_per_sq_ft: 1376,
      description:
        'This beautifully renovated 1 bedroom at the Austin Nichols House is th...',
      image_url:
        'https://www.compass.com/m3/eb5fe0876a14e5d355a1e97276ea53e87b4c2407/64...',
    },
    {
      address: '100 Maspeth Ave',
      apt_num: '4I',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11211,
      neighborhood: 'Williamsburg',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 1,
      bathrooms: 1,
      price: 695000,
      square_feet: 587,
      price_per_sq_ft: 1184,
      description:
        'This is the largest 1 Bedroom line in the building! Corner unit, south...',
      image_url:
        'https://www.compass.com/m/0/017ad8b2-0d7b-48fa-8bb0-df04c7759132/1500x...',
    },
    {
      address: '139 Skillman Ave',
      apt_num: '3C',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11249,
      neighborhood: 'Williamsburg',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 1,
      bathrooms: 1,
      price: 758000,
      square_feet: 637,
      price_per_sq_ft: 1190,
      description:
        'Lots of Amenities & Low Monthlies! This Sun-Flooded Corner Apartment h...',
      image_url:
        'https://www.compass.com/m/d7361a752933a4ef14b1132a0f3d125842c040a6_img...',
    },
    {
      address: '135 N 11th St',
      apt_num: '6A',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11211,
      neighborhood: 'Williamsburg',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 2,
      bathrooms: 2,
      price: 1400000,
      square_feet: 921,
      price_per_sq_ft: 1520,
      description:
        'This 2 Bed 2 Bath Luxury Penthouse has its own Private Terrace with ov...',
      image_url:
        'https://www.compass.com/m/f2d9203192f5e77d4bc8dadb715d4b8e636282df_img...',
    },
    {
      address: '139 Skillman Ave',
      apt_num: '10A',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11211,
      neighborhood: 'Williamsburg',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 3,
      bathrooms: 2,
      price: 2400000,
      square_feet: 1601,
      price_per_sq_ft: 1499,
      description:
        'Full-Floor Penthouse with Panoramic Views of the Manhattan Skyline!  T...',
      image_url:
        'https://www.compass.com/m/00530f6cad4ef5457c5a63b0c893a35ddc89f72f_img...',
    },
    {
      address: '365 Bridge St',
      apt_num: '10D',
      city: 'Brooklyn',
      state: 'NY',
      zip_code: 11201,
      neighborhood: 'Downtown Brooklyn',
      borough: 'Brooklyn',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 3,
      bathrooms: 2,
      price: 1468000,
      square_feet: 1554,
      price_per_sq_ft: 872,
      description:
        'Price Reduced! This 1,554sf Loft has high ceilings and gets gorgeous w...',
      image_url:
        'https://www.compass.com/m3/2a124ab482f81cae29c0a910e3bd4aaa90bd15ec/64...',
    },
    {
      address: '99 John St',
      apt_num: '1114',
      city: 'New York',
      state: 'NY',
      zip_code: 10038,
      neighborhood: 'Financial District',
      borough: 'Manhattan',
      status: 'Sold',
      property_type: 'Condo',
      bedrooms: 1,
      bathrooms: 1,
      price: 869000,
      square_feet: 676,
      price_per_sq_ft: 564,
      description:
        'This unique and modern loft has high, beamed ceilings, south facing su...',
      image_url:
        'https://www.compass.com/m/LISTING_EDITOR/putImages/97f4c0b5-79cd-4260-...',
    },
    {
      address: '231 W 148th St',
      apt_num: '2H',
      city: 'New York',
      state: 'NY',
      zip_code: 10039,
      neighborhood: 'Harlem',
      borough: 'Manhattan',
      status: 'Sold',
      property_type: 'Co-op',
      bedrooms: 2,
      bathrooms: 1,
      price: 610000,
      square_feet: 0,
      price_per_sq_ft: 0,
      description:
        'Fall in love instantly with this stunning two bedroom home, beautifull...',
      image_url:
        'https://www.compass.com/m/LISTING_EDITOR/putImages/ca04458f-3f91-4129-...',
    },
  ];  